Fix "Invalid double value in tf.nn.embeddinglookup
InvalidArgumentError: Value for attr 'Tindices' of double is not in the list of allowed values: int32, int64.
Need to specify data type, like: "np.array(..., dtype=int)"